name: Publish support package

on:
  release:
    types: published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v1
      with:
        python-version: "3.X"

    - name: Set build variables
      id: build-vars
      env:
        TAG_NAME: ${{ github.ref }}
      run: |
        export TAG=$(basename $TAG_NAME)
        echo "TAG=${TAG}"
        export PYTHON_VER="${TAG%-*}"
        export BUILD_NUMBER="${TAG#*-}"

        echo "PYTHON_VER=${PYTHON_VER}"
        echo "BUILD_NUMBER=${BUILD_NUMBER}"

        echo "TAG=${TAG}" >> ${GITHUB_OUTPUT}
        echo "PYTHON_VER=${PYTHON_VER}" >> ${GITHUB_OUTPUT}
        echo "BUILD_NUMBER=${BUILD_NUMBER}" >> ${GITHUB_OUTPUT}

    - name: Update Release Asset to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        python -m pip install -U pip
        python -m pip install -U setuptools
        python -m pip install awscli
        # macOS build
        curl -o macOS-artefact.tar.gz -L https://github.com/beeware/Python-Apple-support/releases/download/${{ steps.build-vars.output.TAG }}/Python-${{ steps.build-vars.output.PY_VERSION }}-macOS-support.${{ steps.build-vars.output.BUILD_NUMBER }}.tar.gz
        aws s3 cp macOS-artefact.tar.gz s3://briefcase-support/python/${{ steps.build-vars.output.PY_VERSION }}/macOS/Python-${{ steps.build-vars.output.PY_VERSION }}-macOS-support.${{ steps.build-vars.output.BUILD_NUMBER }}.tar.gz
        # iOS build
        curl -o iOS-artefact.tar.gz -L https://github.com/beeware/Python-Apple-support/releases/download/${{ steps.build-vars.output.TAG }}/Python-${{ steps.build-vars.output.PY_VERSION }}-iOS-support.${{ steps.build-vars.output.BUILD_NUMBER }}.tar.gz
        aws s3 cp iOS-artefact.tar.gz s3://briefcase-support/python/${{ steps.build-vars.output.PY_VERSION }}/iOS/Python-${{ steps.build-vars.output.PY_VERSION }}-iOS-support.${{ steps.build-vars.output.BUILD_NUMBER }}.tar.gz
        # tvOS build
        curl -o tvOS-artefact.tar.gz -L https://github.com/beeware/Python-Apple-support/releases/download/${{ steps.build-vars.output.TAG }}/Python-${{ steps.build-vars.output.PY_VERSION }}-tvOS-support.${{ steps.build-vars.output.BUILD_NUMBER }}.tar.gz
        aws s3 cp tvOS-artefact.tar.gz s3://briefcase-support/python/${{ steps.build-vars.output.PY_VERSION }}/tvOS/Python-${{ steps.build-vars.output.PY_VERSION }}-tvOS-support.${{ steps.build-vars.output.BUILD_NUMBER }}.tar.gz
        # watchOS build
        curl -o watchOS-artefact.tar.gz -L https://github.com/beeware/Python-Apple-support/releases/download/${{ steps.build-vars.output.TAG }}/Python-${{ steps.build-vars.output.PY_VERSION }}-watchOS-support.${{ steps.build-vars.output.BUILD_NUMBER }}.tar.gz
        aws s3 cp watchOS-artefact.tar.gz s3://briefcase-support/python/${{ steps.build-vars.output.PY_VERSION }}/watchOS/Python-${{ steps.build-vars.output.PY_VERSION }}-watchOS-support.${{ steps.build-vars.output.BUILD_NUMBER }}.tar.gz
